#!/bin/bash

#ps -ef | grep -v grep | grep ruby

if [ -e sinatra.lock ]; then
    echo "lock file exists"
    spid=`cat sinatra.lock`
    kill $spid
    rm sinatra.lock 
fi
   rackup &
   SPID=$! 
   echo "$SPID" >> sinatra.lock 
   echo "Stored pid"
