#!/bin/bash

#ps -ef | grep -v grep | grep ruby

if [ -e sinatra.lock ]; then
    echo "lock file exists"
    spid=`cat sinatra.lock`
    kill $spid
   rm w:w 
else
   rackup &
   SPID=$! 
   $SPID >> sinatra.lock 
   echo "Stored pid"
fi
